/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.crashball;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_icon=0x7f020000;
    }
    public static final class id {
        public static final int ball=0x7f050000;
        public static final int message=0x7f050002;
        public static final int stock_balls=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int game_clear_message=0x7f040005;
        public static final int game_over_message=0x7f040004;
        public static final int hello=0x7f040000;
        public static final int new_ball_help=0x7f040006;
        /**  string name="ready_message">***Hello***</string 
         */
        public static final int pause_message=0x7f040003;
        public static final int ready_message=0x7f040002;
        public static final int stock_ball_count=0x7f040007;
    }
}
